services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: catdb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./mysql:/var/lib/mysql
            - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        ports:
            - 8080:8080
